/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NowRouteImport } from './routes/now'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsWebRouteImport } from './routes/projects.web'
import { Route as ProjectsPythonRouteImport } from './routes/projects.python'
import { Route as ProjectsOctopusRouteImport } from './routes/projects.octopus'
import { Route as ProjectsJavaRouteImport } from './routes/projects.java'
import { Route as ProjectsDesignRouteImport } from './routes/projects.design'
import { Route as ProjectsVetCareRouteImport } from './routes/projects.VetCare'
import { Route as ProjectsRoPaScRouteImport } from './routes/projects.RoPaSc'
import { Route as ProjectsIECDRouteImport } from './routes/projects.IECD'
import { Route as ProjectsIASARouteImport } from './routes/projects.IASA'
import { Route as ProjectsChaosGameRouteImport } from './routes/projects.ChaosGame'
import { Route as Projects3dRouteImport } from './routes/projects.3d'

const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsWebRoute = ProjectsWebRouteImport.update({
  id: '/projects/web',
  path: '/projects/web',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPythonRoute = ProjectsPythonRouteImport.update({
  id: '/projects/python',
  path: '/projects/python',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOctopusRoute = ProjectsOctopusRouteImport.update({
  id: '/projects/octopus',
  path: '/projects/octopus',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsJavaRoute = ProjectsJavaRouteImport.update({
  id: '/projects/java',
  path: '/projects/java',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDesignRoute = ProjectsDesignRouteImport.update({
  id: '/projects/design',
  path: '/projects/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsVetCareRoute = ProjectsVetCareRouteImport.update({
  id: '/projects/VetCare',
  path: '/projects/VetCare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoPaScRoute = ProjectsRoPaScRouteImport.update({
  id: '/projects/RoPaSc',
  path: '/projects/RoPaSc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIECDRoute = ProjectsIECDRouteImport.update({
  id: '/projects/IECD',
  path: '/projects/IECD',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIASARoute = ProjectsIASARouteImport.update({
  id: '/projects/IASA',
  path: '/projects/IASA',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsChaosGameRoute = ProjectsChaosGameRouteImport.update({
  id: '/projects/ChaosGame',
  path: '/projects/ChaosGame',
  getParentRoute: () => rootRouteImport,
} as any)
const Projects3dRoute = Projects3dRouteImport.update({
  id: '/projects/3d',
  path: '/projects/3d',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/now': typeof NowRoute
  '/projects/3d': typeof Projects3dRoute
  '/projects/ChaosGame': typeof ProjectsChaosGameRoute
  '/projects/IASA': typeof ProjectsIASARoute
  '/projects/IECD': typeof ProjectsIECDRoute
  '/projects/RoPaSc': typeof ProjectsRoPaScRoute
  '/projects/VetCare': typeof ProjectsVetCareRoute
  '/projects/design': typeof ProjectsDesignRoute
  '/projects/java': typeof ProjectsJavaRoute
  '/projects/octopus': typeof ProjectsOctopusRoute
  '/projects/python': typeof ProjectsPythonRoute
  '/projects/web': typeof ProjectsWebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/now': typeof NowRoute
  '/projects/3d': typeof Projects3dRoute
  '/projects/ChaosGame': typeof ProjectsChaosGameRoute
  '/projects/IASA': typeof ProjectsIASARoute
  '/projects/IECD': typeof ProjectsIECDRoute
  '/projects/RoPaSc': typeof ProjectsRoPaScRoute
  '/projects/VetCare': typeof ProjectsVetCareRoute
  '/projects/design': typeof ProjectsDesignRoute
  '/projects/java': typeof ProjectsJavaRoute
  '/projects/octopus': typeof ProjectsOctopusRoute
  '/projects/python': typeof ProjectsPythonRoute
  '/projects/web': typeof ProjectsWebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/now': typeof NowRoute
  '/projects/3d': typeof Projects3dRoute
  '/projects/ChaosGame': typeof ProjectsChaosGameRoute
  '/projects/IASA': typeof ProjectsIASARoute
  '/projects/IECD': typeof ProjectsIECDRoute
  '/projects/RoPaSc': typeof ProjectsRoPaScRoute
  '/projects/VetCare': typeof ProjectsVetCareRoute
  '/projects/design': typeof ProjectsDesignRoute
  '/projects/java': typeof ProjectsJavaRoute
  '/projects/octopus': typeof ProjectsOctopusRoute
  '/projects/python': typeof ProjectsPythonRoute
  '/projects/web': typeof ProjectsWebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/now'
    | '/projects/3d'
    | '/projects/ChaosGame'
    | '/projects/IASA'
    | '/projects/IECD'
    | '/projects/RoPaSc'
    | '/projects/VetCare'
    | '/projects/design'
    | '/projects/java'
    | '/projects/octopus'
    | '/projects/python'
    | '/projects/web'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/now'
    | '/projects/3d'
    | '/projects/ChaosGame'
    | '/projects/IASA'
    | '/projects/IECD'
    | '/projects/RoPaSc'
    | '/projects/VetCare'
    | '/projects/design'
    | '/projects/java'
    | '/projects/octopus'
    | '/projects/python'
    | '/projects/web'
  id:
    | '__root__'
    | '/'
    | '/now'
    | '/projects/3d'
    | '/projects/ChaosGame'
    | '/projects/IASA'
    | '/projects/IECD'
    | '/projects/RoPaSc'
    | '/projects/VetCare'
    | '/projects/design'
    | '/projects/java'
    | '/projects/octopus'
    | '/projects/python'
    | '/projects/web'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NowRoute: typeof NowRoute
  Projects3dRoute: typeof Projects3dRoute
  ProjectsChaosGameRoute: typeof ProjectsChaosGameRoute
  ProjectsIASARoute: typeof ProjectsIASARoute
  ProjectsIECDRoute: typeof ProjectsIECDRoute
  ProjectsRoPaScRoute: typeof ProjectsRoPaScRoute
  ProjectsVetCareRoute: typeof ProjectsVetCareRoute
  ProjectsDesignRoute: typeof ProjectsDesignRoute
  ProjectsJavaRoute: typeof ProjectsJavaRoute
  ProjectsOctopusRoute: typeof ProjectsOctopusRoute
  ProjectsPythonRoute: typeof ProjectsPythonRoute
  ProjectsWebRoute: typeof ProjectsWebRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/web': {
      id: '/projects/web'
      path: '/projects/web'
      fullPath: '/projects/web'
      preLoaderRoute: typeof ProjectsWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/python': {
      id: '/projects/python'
      path: '/projects/python'
      fullPath: '/projects/python'
      preLoaderRoute: typeof ProjectsPythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/octopus': {
      id: '/projects/octopus'
      path: '/projects/octopus'
      fullPath: '/projects/octopus'
      preLoaderRoute: typeof ProjectsOctopusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/java': {
      id: '/projects/java'
      path: '/projects/java'
      fullPath: '/projects/java'
      preLoaderRoute: typeof ProjectsJavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/design': {
      id: '/projects/design'
      path: '/projects/design'
      fullPath: '/projects/design'
      preLoaderRoute: typeof ProjectsDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/VetCare': {
      id: '/projects/VetCare'
      path: '/projects/VetCare'
      fullPath: '/projects/VetCare'
      preLoaderRoute: typeof ProjectsVetCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/RoPaSc': {
      id: '/projects/RoPaSc'
      path: '/projects/RoPaSc'
      fullPath: '/projects/RoPaSc'
      preLoaderRoute: typeof ProjectsRoPaScRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/IECD': {
      id: '/projects/IECD'
      path: '/projects/IECD'
      fullPath: '/projects/IECD'
      preLoaderRoute: typeof ProjectsIECDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/IASA': {
      id: '/projects/IASA'
      path: '/projects/IASA'
      fullPath: '/projects/IASA'
      preLoaderRoute: typeof ProjectsIASARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/ChaosGame': {
      id: '/projects/ChaosGame'
      path: '/projects/ChaosGame'
      fullPath: '/projects/ChaosGame'
      preLoaderRoute: typeof ProjectsChaosGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/3d': {
      id: '/projects/3d'
      path: '/projects/3d'
      fullPath: '/projects/3d'
      preLoaderRoute: typeof Projects3dRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NowRoute: NowRoute,
  Projects3dRoute: Projects3dRoute,
  ProjectsChaosGameRoute: ProjectsChaosGameRoute,
  ProjectsIASARoute: ProjectsIASARoute,
  ProjectsIECDRoute: ProjectsIECDRoute,
  ProjectsRoPaScRoute: ProjectsRoPaScRoute,
  ProjectsVetCareRoute: ProjectsVetCareRoute,
  ProjectsDesignRoute: ProjectsDesignRoute,
  ProjectsJavaRoute: ProjectsJavaRoute,
  ProjectsOctopusRoute: ProjectsOctopusRoute,
  ProjectsPythonRoute: ProjectsPythonRoute,
  ProjectsWebRoute: ProjectsWebRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
